/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_levmartest_HelloJni */

#ifndef _Included_com_example_levmartest_HelloJni
#define _Included_com_example_levmartest_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_levmartest_HelloJni
 * Method:    test
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_levmartest_HelloJni_test
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
